"""Add time range to VRDVideo and ObjectVideo

Revision ID: 1c928b4ae412
Revises: ab427dff7f04
Create Date: 2026-06-12 02:25:51.743979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c928b4ae412'
down_revision: Union[str, Sequence[str], None] = 'ab427dff7f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object_videos', sa.Column('start_time', sa.Integer(), nullable=True))
    op.add_column('object_videos', sa.Column('end_time', sa.Integer(), nullable=True))
    op.add_column('vrd_videos', sa.Column('start_time', sa.Integer(), nullable=True))
    op.add_column('vrd_videos', sa.Column('end_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vrd_videos', 'end_time')
    op.drop_column('vrd_videos', 'start_time')
    op.drop_column('object_videos', 'end_time')
    op.drop_column('object_videos', 'start_time')
    # ### end Alembic commands ###
