"""Add new models

Revision ID: 25a444cfacd6
Revises: 3f7f1d2e9b10
Create Date: 2026-06-18 00:47:25.215201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25a444cfacd6'
down_revision: Union[str, Sequence[str], None] = '3f7f1d2e9b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('vector_metadata_vector_id_key'), 'vector_metadata', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('vector_metadata_vector_id_key'), 'vector_metadata', ['vector_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
