"""Add time range to VRDVideo and ObjectVideo

Revision ID: 262e0fd8c58c
Revises: 34f71f074933
Create Date: 2026-06-24 18:26:14.896452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '262e0fd8c58c'
down_revision: Union[str, Sequence[str], None] = '34f71f074933'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ocr_words', sa.Column('word_detection_model', sa.String(), nullable=False))
    op.add_column('ocr_words', sa.Column('word_recognition_model', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ocr_words', 'word_recognition_model')
    op.drop_column('ocr_words', 'word_detection_model')
    # ### end Alembic commands ###
