"""Add time range to VRDVideo and ObjectVideo

Revision ID: 27e4a04ebcfc
Revises: c0c097c5c805
Create Date: 2026-06-21 03:02:50.710420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27e4a04ebcfc'
down_revision: Union[str, Sequence[str], None] = 'c0c097c5c805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocr_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('end_time', sa.Integer(), nullable=True),
    sa.Column('frame_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_words_id'), 'ocr_words', ['id'], unique=False)
    op.create_index(op.f('ix_ocr_words_video_id'), 'ocr_words', ['video_id'], unique=False)
    op.create_index(op.f('ix_ocr_words_word'), 'ocr_words', ['word'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ocr_words_word'), table_name='ocr_words')
    op.drop_index(op.f('ix_ocr_words_video_id'), table_name='ocr_words')
    op.drop_index(op.f('ix_ocr_words_id'), table_name='ocr_words')
    op.drop_table('ocr_words')
    # ### end Alembic commands ###
