"""Add time range to VRDVideo and ObjectVideo

Revision ID: 2b5b7190e5e3
Revises: 27e4a04ebcfc
Create Date: 2026-06-21 06:52:30.253716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b5b7190e5e3'
down_revision: Union[str, Sequence[str], None] = '27e4a04ebcfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object_videos', sa.Column('frame_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('object_videos', 'frame_number')
    # ### end Alembic commands ###
