"""Add time range to VRDVideo and ObjectVideo

Revision ID: 2c64e8ddf4c1
Revises: 25a444cfacd6
Create Date: 2026-06-19 22:35:50.794222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c64e8ddf4c1'
down_revision: Union[str, Sequence[str], None] = '25a444cfacd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
