"""Add model_name to ObjectVideo

Revision ID: 32e20aef926f
Revises: 262e0fd8c58c
Create Date: 2026-06-24 23:44:56.105723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32e20aef926f'
down_revision: Union[str, Sequence[str], None] = '262e0fd8c58c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object_videos', sa.Column('model_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('object_videos', 'model_name')
    # ### end Alembic commands ###
