"""Add time range to VRDVideo and ObjectVideo

Revision ID: 34f71f074933
Revises: 90e1897d3847
Create Date: 2026-06-21 08:19:03.770976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34f71f074933'
down_revision: Union[str, Sequence[str], None] = '90e1897d3847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vrd_videos', sa.Column('frame_time', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vrd_videos', 'frame_time')
    # ### end Alembic commands ###
