"""Create initial database schema

Revision ID: ab427dff7f04
Revises: 
Create Date: 2026-06-11 20:15:58.391980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab427dff7f04'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objects_id'), 'objects', ['id'], unique=False)
    op.create_index(op.f('ix_objects_key'), 'objects', ['key'], unique=False)
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_index(op.f('ix_videos_file_name'), 'videos', ['file_name'], unique=False)
    op.create_index(op.f('ix_videos_id'), 'videos', ['id'], unique=False)
    op.create_table('vrd_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vrd_objects_id'), 'vrd_objects', ['id'], unique=False)
    op.create_index(op.f('ix_vrd_objects_key'), 'vrd_objects', ['key'], unique=False)
    op.create_table('vrd_predicates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vrd_predicates_id'), 'vrd_predicates', ['id'], unique=False)
    op.create_index(op.f('ix_vrd_predicates_key'), 'vrd_predicates', ['key'], unique=False)
    op.create_table('vrd_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vrd_subjects_id'), 'vrd_subjects', ['id'], unique=False)
    op.create_index(op.f('ix_vrd_subjects_key'), 'vrd_subjects', ['key'], unique=False)
    op.create_table('object_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_object_videos_id'), 'object_videos', ['id'], unique=False)
    op.create_index(op.f('ix_object_videos_object_id'), 'object_videos', ['object_id'], unique=False)
    op.create_index(op.f('ix_object_videos_video_id'), 'object_videos', ['video_id'], unique=False)
    op.create_table('vrd_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('predicate_id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['vrd_objects.id'], ),
    sa.ForeignKeyConstraint(['predicate_id'], ['vrd_predicates.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['vrd_subjects.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vrd_videos_id'), 'vrd_videos', ['id'], unique=False)
    op.create_index(op.f('ix_vrd_videos_object_id'), 'vrd_videos', ['object_id'], unique=False)
    op.create_index(op.f('ix_vrd_videos_predicate_id'), 'vrd_videos', ['predicate_id'], unique=False)
    op.create_index(op.f('ix_vrd_videos_subject_id'), 'vrd_videos', ['subject_id'], unique=False)
    op.create_index(op.f('ix_vrd_videos_video_id'), 'vrd_videos', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vrd_videos_video_id'), table_name='vrd_videos')
    op.drop_index(op.f('ix_vrd_videos_subject_id'), table_name='vrd_videos')
    op.drop_index(op.f('ix_vrd_videos_predicate_id'), table_name='vrd_videos')
    op.drop_index(op.f('ix_vrd_videos_object_id'), table_name='vrd_videos')
    op.drop_index(op.f('ix_vrd_videos_id'), table_name='vrd_videos')
    op.drop_table('vrd_videos')
    op.drop_index(op.f('ix_object_videos_video_id'), table_name='object_videos')
    op.drop_index(op.f('ix_object_videos_object_id'), table_name='object_videos')
    op.drop_index(op.f('ix_object_videos_id'), table_name='object_videos')
    op.drop_table('object_videos')
    op.drop_index(op.f('ix_vrd_subjects_key'), table_name='vrd_subjects')
    op.drop_index(op.f('ix_vrd_subjects_id'), table_name='vrd_subjects')
    op.drop_table('vrd_subjects')
    op.drop_index(op.f('ix_vrd_predicates_key'), table_name='vrd_predicates')
    op.drop_index(op.f('ix_vrd_predicates_id'), table_name='vrd_predicates')
    op.drop_table('vrd_predicates')
    op.drop_index(op.f('ix_vrd_objects_key'), table_name='vrd_objects')
    op.drop_index(op.f('ix_vrd_objects_id'), table_name='vrd_objects')
    op.drop_table('vrd_objects')
    op.drop_index(op.f('ix_videos_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_file_name'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_objects_key'), table_name='objects')
    op.drop_index(op.f('ix_objects_id'), table_name='objects')
    op.drop_table('objects')
    # ### end Alembic commands ###
