"""Add time range to VRDVideo and ObjectVideo

Revision ID: c0c097c5c805
Revises: 2c64e8ddf4c1
Create Date: 2026-06-21 02:57:18.395671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0c097c5c805'
down_revision: Union[str, Sequence[str], None] = '2c64e8ddf4c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
