"""Add time range to VRDVideo and ObjectVideo

Revision ID: d279b23a2b08
Revises: 2b5b7190e5e3
Create Date: 2026-06-21 07:04:13.768674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd279b23a2b08'
down_revision: Union[str, Sequence[str], None] = '2b5b7190e5e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object_videos', sa.Column('frame_time', sa.Integer(), nullable=True))
    op.drop_column('object_videos', 'frame_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object_videos', sa.Column('frame_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('object_videos', 'frame_time')
    # ### end Alembic commands ###
